# Generated by Django 3.2.7 on 2021-10-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211009_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(default='', max_length=6),
        ),
    ]
