# Generated by Django 3.2.7 on 2021-10-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211009_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ordered_address',
            old_name='Name',
            new_name='name',
        ),
    ]
