# Generated by Django 3.2.7 on 2021-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211009_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Ordered_Address',
        ),
    ]
