# Generated by Django 3.2.7 on 2021-10-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20211009_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_adrress',
            field=models.BooleanField(default=False),
        ),
    ]
