# Generated by Django 3.2.7 on 2021-10-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_address_delivery_adrress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='delivery_adrress',
            new_name='delivery_address',
        ),
    ]
